# -*- coding: utf-8 -*-
"""SE Ver 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T8B3uKWQheKgEm6ku25x-r6uF_tVfIpo
"""

a=2
b=3
c=4
x=5.5
y=a*x*x+b*x+c
print('The value of y is ',y)